=== DemjanCsongor/SZ7MGG_XMLGyak/SZ7MGG_0928/demo/DCS_kurzusfelvetel/DCS_kurzusfelvetel.dtd
<?xml version="1.0"?>

<!ELEMENT DCS_kurzusfelvetel (hallgato, kurzusok)>

        <!ATTLIST DCS_kurzusfelvetel
        tanev CDATA #REQUIRED
        egyetem CDATA #FIXED "ME"
<!ELEMENT hallgato (hnev, szulev, szak*)>
        <!ATTLIST hallgato
                id ID #REQUIRED>

<!ELEMENT hnev (#PCDATA)>
<!ELEMENT szulev (#PCDATA)>
<!ELEMENT szak (#PCDATA)>
        <!ATTLIST szak
                evf CDATA #FIXED "5">

<!ELEMENT kurzusok (kurzus*)>

<!ELEMENT kurzus (kurzusnev+, kredit, hely, idopont+, oktato?, oraado?)>
        <!ATTLIST kurzus
                id ID #REQUIRED
                nyelv CDATA
                jovahagyas CDATA "nem">

<!ELEMENT kurzusnev (#PCDATA)>
<!ELEMENT kredit (#PCDATA)>
<!ELEMENT hely (#PCDATA)>
<!ELEMENT idopont (#PCDATA)>
<!ELEMENT oktato (#PCDATA)>
<!ELEMENT oraado (#PCDATA)>
>

=== DemjanCsongor/SZ7MGG_XMLGyak/SZ7MGG_0928/demo/DCS_kurzusfelvetel/DCS_kurzusfelvetel.xml
<?xml version = "1.0" encoding = "utf-8"?>

<!DOCTYPE DCS_kurzusfelvetel SYSTEM "DCS_kurzusfelvetel.dtd">

<DCS_kurzusfelvetel tanev="2022_2023 I." egyetem="ME">

    <hallgato id="SZ7MGG.ME">
        <hnev>Demján Csongor</hnev>
        <szulev>2000-11-10</szulev>
        <szak evf="5">Programtervező informatikus</szak>
    </hallgato>

    <kurzusok>

        <kurzus id="GEIAL332-B">
            <kurzusnev>Adatkezelés XML környezetben</kurzusnev>
            <kredit>5</kredit>
            <hely>XXXII.</hely>
            <idopont>Kedd 12:00-13:30</idopont>
            <oktato>Dr. Bednarik László</oktato>
        </kurzus>
        <kurzus id="GEIAL322-B" jovahagyas="igen">
            <kurzusnev>Adatbázis rendszerek I.</kurzusnev>
            <kredit>5</kredit>
            <hely>In101</hely>
            <idopont>Kedd 8:00-9:30</idopont>
            <oktato>Dr. Kovács László</oktato>
        </kurzus>
        <kurzus id="GEIAL333-B" nyelv="angol">
            <kurzusnev>Webalkalmazás fejlesztés - Java</kurzusnev>
            <kredit>5</kredit>
            <hely>In103</hely>
            <idopont>Csütörtök 8:00-9:30</idopont>
            <oktato>Dr. Barabás Péter</oktato>
            <oraado>Tóth Bence</oraado>
        </kurzus>
    </kurzusok>

</DCS_kurzusfelvetel>
